---
blank_issues_enabled: false
contact_links:
  - name: Make It For Everyone Community Support
    url: https://github.com/developer-academy-unina/Workshop-Make-It-For-Everyone/discussions
    about: Please ask and answer questions here.
